CREATE TABLE CURSO(
CURCODIGO BIGINT PRIMARY KEY,
CURNOME VARCHAR(100) NOT NULL
);

           
CREATE TABLE ALUNO(
ALCODIGO BIGINT PRIMARY KEY,
ALNOME VARCHAR(100) NOT NULL,
ALDATANASC DATE NOT NULL,
ALRENDA NUMERIC(10,2) NOT NULL,
CURCODIGO BIGINT NOT NULL,
FOREIGN KEY (CURCODIGO) REFERENCES CURSO (CURCODIGO)
);

CREATE TABLE DISCIPLINA(
DISCODIGO BIGINT PRIMARY KEY,
DISNOME VARCHAR(100) NOT NULL
);

CREATE TABLE CURDIS (
CURCODIGO BIGINT NOT NULL,
DISCODIGO BIGINT NOT NULL,
FOREIGN KEY (CURCODIGO) REFERENCES CURSO,
FOREIGN KEY (DISCODIGO) REFERENCES DISCIPLINA
);



INSERT INTO CURSO(CURCODIGO, CURNOME) VALUES
(10,'INFORMÁTICA');

INSERT INTO CURSO(CURCODIGO, CURNOME) VALUES
(20,'AGROINDÚSTRIA');

INSERT INTO CURSO(CURCODIGO, CURNOME) VALUES
(30,'AGROPECUÁRIA');

SELECT *  FROM CURSO
WHERE CURCODIGO = 10 AND
      CURCODIGO = 20;


      
INSERT INTO ALUNO (ALCODIGO, ALNOME, ALDATANASC, ALRENDA, CURCODIGO)
VALUES (1000, 'DOUGLAS', '09/10/1998', 788.000, 10);

SELECT * FROM ALUNO



INSERT INTO DISCIPLINA (DISCODIGO, DISNOME)
VALUES (100,'MATEMÁTICA');

INSERT INTO DISCIPLINA (DISCODIGO, DISNOME)
VALUES (200,'BANCO DE DADOS I');

INSERT INTO DISCIPLINA (DISCODIGO, DISNOME)
VALUES (300,'BANCO DE DADOS II');

SELECT * FROM DISCIPLINA 



INSERT INTO CURDIS(CURCODIGO,DISCODIGO) VALUES
(30,100);

INSERT INTO CURDIS(CURCODIGO,DISCODIGO) VALUES
(10,100);

INSERT INTO CURDIS(CURCODIGO,DISCODIGO) VALUES
(20,100);

SELECT * FROM CURDIS

UPDATE ALUNO
SET ALRENDA = 500.00,
    CURCODIGO = 20,
    ALNOME = 'DOUGLAS MEDEIROS'
WHERE ALCODIGO = 1000;

SELECT * FROM ALUNO

DELETE FROM CURDIS
WHERE CURCODIGO = 30;

SELECT * FROM CURDIS

CREATE TABLE PREREQUISITO(
LIBERADA BIGINT NOT NULL,
LIBERADORA BIGINT NOT NULL,
FOREIGN KEY (LIBERADA) REFERENCES DISCIPLINA,
FOREIGN KEY (LIBERADORA) REFERENCES DISCIPLINA
);

INSERT INTO PREREQUISITO (LIBERADA,LIBERADORA)
VALUES (300,200);

SELECT * FROM PREREQUISITO


